let one = document.getElementById("age-table");
let two = document.getElementById("age-list").children;
let three = document.querySelector("td");
let four = document.querySelector("[type='submit']");
let five = document.querySelector("input");
console.log(one);
console.log(two);
console.log(three);
console.log(four);
console.log(five);
